version: "3.8"
services:
  signaling-server:
    container_name: webrtc-signaling-server
    build: .
    restart: always
    ports:
      - "4242:4242"
    environment:
      - PORT=4242
    networks:
      - webrtc-network

networks:
  webrtc-network:
    driver: bridge
